services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta padrão do RabbitMQ
      - "15672:15672" # Porta do painel de administração do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest  # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados
    networks:
      - monitoring           
      
  # .API CONTACT
  contact-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AddContact.API/Dockerfile
    container_name: addcontact_app
    restart: always
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 
    networks:
      - monitoring      
   
    
  # Area Code
  area-code-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AreaCode.API/Dockerfile
    container_name: addareacode_app
    restart: always
    ports:
      - "5006:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - monitoring           

volumes:
  rabbitmq_data:

networks:
  monitoring: