services:
               
  # .API CONTACT
  contact-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AddContact.API/Dockerfile
    container_name: addcontact_app
    restart: always
    ports:
      - "5011:5011"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker" 
    networks:
      - techchallenge-worker-persistency_custom_network      
     
  # Area Code
  area-code-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AreaCode.API/Dockerfile
    container_name: addareacode_app
    restart: always
    ports:
      - "5012:5012"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    networks:
      - techchallenge-worker-persistency_custom_network           

networks:
  techchallenge-worker-persistency_custom_network:
    external: true