services:           
  # .API CONTACT
  contact-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AddContact.API/Dockerfile
    container_name: addcontact_app
    restart: always
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network
    
  # Area Code
  area-code-api:
    build:
      context: .
      dockerfile: src/01-API/PosTech.Fase3.AreaCode.API/Dockerfile
    container_name: addareacode_app
    restart: always
    ports:
      - "59464:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      rabbitmq_host: "rabbitmq"  # Nome do container RabbitMQ
      rabbitmq_user: "5672"
    networks:
      - techchallenge-postech-4nett-fasetres-worker-persistency_custom_network

# volumes:
#   rabbitmq_data:

networks:  
  techchallenge-postech-4nett-fasetres-worker-persistency_custom_network:
    external: true