version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta padrão do RabbitMQ
      - "15672:15672" # Porta do painel de administração do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest  # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"   # Porta padrão do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root   # Defina a senha do usuário root
      MYSQL_DATABASE: protocol_database          # Nome do banco de dados inicial
      MYSQL_USER: user                 # Nome do usuário
      MYSQL_PASSWORD: user123        # Senha do usuário
    volumes:
      - mysql_data:/var/lib/mysql          # Persistência de dados

volumes:
  rabbitmq_data:
  mysql_data: