apiVersion: v1
kind: Secret
metadata:
  name: hackathon-pacientes-secret
type: Opaque
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL2ZpYXA6ZmlhcDEyMzQ1NkBzZXJ2aWNlLW1vbmdvLWRiOjI3MDE3L2FkbWlu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-pacientes
  labels:
    app: hackathon-pacientes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-pacientes
  template:
    metadata:
      labels:
        app: hackathon-pacientes
    spec:
      containers:
        - name: container-hackathon-pacientes
          image: tatianacardoso/fiap-paciente-api:5
          ports:
            - containerPort: 5013         
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: hackathon-pacientes-secret
                  key: MONGO_CONNECTION_STRING            
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: service-hackathon-pacientes
  labels:
    app: hackathon-pacientes
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5013
      nodePort: 31003
  selector:
    app: hackathon-pacientes